In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns

In [2]:
from dfcrea import crea_df

df_art = crea_df('Artículos - Lista.csv')

In [3]:
df_art.tail()

,,EAN,Referencia,,Nombre,Coste,Precio,,P.V.P.,Beneficio,%MC,%MV,Stock,,Proveedor,Clasificación,
8818,Normal,3181730332221,1157418,,WILLIAMS MASAJE AQUA VELVA 100ML,"2,505 ","3,30 ",21 %,"3,99 ","0,80 ","31,7 %","24,1 %",-5,0,"SENSOGREEN HEALTHCARE, S.L",MASAJES Y AFTER SHAVE,
8819,Normal,6973512356863,,,XINQUEEN MASCARILLA FFP2 AZUL,"0,280 ","0,83 ",21 %,"1,00 ","0,55 ","196,4 %","66,3 %",-6,452,COVALDROPER GRUPO,,
8820,Normal,6973512356016,,,XINQUEEN MASCARILLA FFP2 AZUL 20UD,"5,600 ","16,53 ",21 %,"20,00 ","10,93 ","195,2 %","66,1 %",0,-1,COVALDROPER GRUPO,,
8821,Actualizado desde fichero o API,8420822123886,,,ZAS BAÑOS RECAMBIO LIMP,"1,214 ","2,14 ",21 %,"2,59 ","0,93 ","76,3 %","43,3 %",0,839,DPH S. L .,LIMPIEZA,
8822,Actualizado desde fichero o API,8420236031517,1005994,,ZUM INSECTICIDA RASTREROS CUCARACHAS 800C.C. A...,"4,477 ","6,60 ",21 %,"7,99 ","2,12 ","47,4 %","32,2 %",-101,8,GROSSEN VERBRAUCH,LIMPIEZA,

In [4]:
df_art = df_art.iloc[:, 1:]

In [5]:
df_art.columns

Index(['EAN', 'Referencia', '', 'Nombre', 'Coste', 'Precio', '', 'P.V.P.',
       'Beneficio', '%MC', '%MV', 'Stock', '', 'Proveedor', 'Clasificación',
       ''],
      dtype='object')

In [6]:
df_art.columns

Index(['EAN', 'Referencia', '', 'Nombre', 'Coste', 'Precio', '', 'P.V.P.',
       'Beneficio', '%MC', '%MV', 'Stock', '', 'Proveedor', 'Clasificación',
       ''],
      dtype='object')

In [7]:
df_art.columns = ['EAN', 'Referencia', 'tirar1', 'Nombre', 'Coste', 'Precio', 'tipo_IVA', 'P.V.P.',
       'Beneficio', '%MC', '%MV', 'Stock', 'Dias_ultima_venta', 'Proveedor', 'Clasificación',
       'tirar2']

In [8]:
df_art = df_art.drop(columns = ['tirar1', 'tirar2'])

In [9]:
df_art.Dias_ultima_venta = df_art.Dias_ultima_venta.str.replace('.', '')
df_art = df_art.replace('%', '')
df_art

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
0,8411056267569,,ABONO LIQ GESAL 1000ML,"2,461 ","4,12 ",21 %,"4,99 ","1,66 ","67,4 %","40,3 %",-3,19,BEMALU,LIMPIEZA
1,8412078010102,,ABRILLANTADOR CARAMBA 750MLCOL,"2,678 ","4,12 ",21 %,"4,99 ","1,44 ","53,9 %","35,0 %",0,1007,DPH S. L .,LIMPIEZA
2,8001480710450,,ACE LEJIA+DETERGENTE 2LTO,"1,126 ","1,64 ",21 %,"1,99 ","0,51 ","45,6 %","31,3 %",0,556,DPH S. L .,LIMPIEZA
3,3600522215455,1033902,ACEITE CAPILAR ELVIVE EXTRAORDINARIO 100ML,"6,128 ","6,57 ",21 %,"7,95 ","0,44 ","7,2 %","6,7 %",3,10,LOREAL CONSUMO,ASEO PERSONAL
4,6001159111993,1073141,ACEITE CORP BIO OIL 60ML,"6,156 ","8,22 ",21 %,"9,95 ","2,06 ","33,5 %","25,1 %",0,479,NAYPES,COSMETICA CONSUMO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8818,3181730332221,1157418,WILLIAMS MASAJE AQUA VELVA 100ML,"2,505 ","3,30 ",21 %,"3,99 ","0,80 ","31,7 %","24,1 %",-5,0,"SENSOGREEN HEALTHCARE, S.L",MASAJES Y AFTER SHAVE
8819,6973512356863,,XINQUEEN MASCARILLA FFP2 AZUL,"0,280 ","0,83 ",21 %,"1,00 ","0,55 ","196,4 %","66,3 %",-6,452,COVALDROPER GRUPO,
8820,6973512356016,,XINQUEEN MASCARILLA FFP2 AZUL 20UD,"5,600 ","16,53 ",21 %,"20,00 ","10,93 ","195,2 %","66,1 %",0,-1,COVALDROPER GRUPO,
8821,8420822123886,,ZAS BAÑOS RECAMBIO LIMP,"1,214 ","2,14 ",21 %,"2,59 ","0,93 ","76,3 %","43,3 %",0,839,DPH S. L .,LIMPIEZA
8822,8420236031517,1005994,ZUM INSECTICIDA RASTREROS CUCARACHAS 800C.C. A...,"4,477 ","6,60 ",21 %,"7,99 ","2,12 ","47,4 %","32,2 %",-101,8,GROSSEN VERBRAUCH,LIMPIEZA

In [10]:
# df_art.info() # todas las variables son tipo objeto
# type(df_art.Coste[0]) # los datos de la variable Coste son strings

In [11]:
import re

for col in df_art[['Coste','Precio', 'tipo_IVA', 'P.V.P.', 'Beneficio', '%MC', '%MV']].columns:
    df_art[col] = df_art[col].str.replace(',', '.')
    df_art[col] = df_art[col].apply(lambda x: re.findall(r'[\.\d]+', x)[0])  # de primeras "re.findall(r'[\.\d]+', x)" me devuelve una lista con el numero dentro, asi que haciendo [0] obtengo el numero sin el formato lista
    
df_art.head()

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
0,8411056267569,,ABONO LIQ GESAL 1000ML,2.461,4.12,21,4.99,1.66,67.4,40.3,-3,19,BEMALU,LIMPIEZA
1,8412078010102,,ABRILLANTADOR CARAMBA 750MLCOL,2.678,4.12,21,4.99,1.44,53.9,35.0,0,1007,DPH S. L .,LIMPIEZA
2,8001480710450,,ACE LEJIA+DETERGENTE 2LTO,1.126,1.64,21,1.99,0.51,45.6,31.3,0,556,DPH S. L .,LIMPIEZA
3,3600522215455,1033902,ACEITE CAPILAR ELVIVE EXTRAORDINARIO 100ML,6.128,6.57,21,7.95,0.44,7.2,6.7,3,10,LOREAL CONSUMO,ASEO PERSONAL
4,6001159111993,1073141,ACEITE CORP BIO OIL 60ML,6.156,8.22,21,9.95,2.06,33.5,25.1,0,479,NAYPES,COSMETICA CONSUMO

# Análisis por "REFERENCIA":

In [12]:
print(df_art.groupby('Referencia').size()[''])
# hay 2343 articulos SIN REFERENCIA
2343/len(df_art)

2343

0.26555593335600136

In [13]:
L = df_art.Referencia.unique()
ref_raras = []
for ref in L:
    if len(re.findall(r'\D', ref)) > 0:
        ref_raras.append(ref)
        
len(ref_raras)
# hay 12 referencias que no son simplemente numeros

12

# Análisis por "NOMBRE":

In [14]:
print(len(df_art) - len(df_art.groupby('Nombre')))

df_art.groupby('Nombre').size().sort_values(ascending = False)
# hay 19 nombres repetidos entre los articulos (los 19 primeros de la siguiente serie)

19

Nombre
LIMP DESINF SANICENTRO 1500ML                           2
FUNDA ROPA 60X137                                       2
AGUA OXIGENADA KELSIA 1000ML                            2
GUANTES NITRILO SEMPERCARE 200UD GDE                    2
ANTIPOL CHINO                                           2
                                                       ..
COL TOUS ONIX ESTUCHE 3PZAS61.16                        1
COL TOUS EDT 90V SRA                                    1
COL TOUS EDP 90V SRA                                    1
COL TOUS BABY VERDE 100VAP INF                          1
ZUM INSECTICIDA RASTREROS CUCARACHAS 800C.C. ACCUSOL    1
Length: 8804, dtype: int64

In [15]:
df_art[df_art.Nombre == 'LIMP DESINF SANICENTRO 1500ML']
# ejemplo de articulos con el mismo nombre (y tambien mismo EAN) pero con caracteristicas ligeramente distintas

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
5803,8401931011648,,LIMP DESINF SANICENTRO 1500ML,1.295,2.06,21,2.49,0.77,59.1,37.1,0,861,DPH S. L .,LIMPIEZA
5804,8410931011648,,LIMP DESINF SANICENTRO 1500ML,1.243,2.47,21,2.99,1.23,98.7,49.7,12,664,DPH S. L .,LIMPIEZA

# Análisis por "TIPO_IVA":

In [16]:
df_art.groupby('tipo_IVA').size()
# la gran mayoria tienen el 21% de iva

tipo_IVA
...      25
10       58
21     8720
4        20
dtype: int64

In [17]:
df_art.tipo_IVA.unique()[2]
# 25 articulos no tienen especificado el iva (¿o no se les aplica iva?) y viene denotado con puntos suspensivos

'...'

# Análisis por "PROVEEDOR":

In [18]:
df_art.groupby('Proveedor').size().sort_values(ascending = False)
# 121 proveedores

Proveedor
DPH S. L .                                            745
LOREAL CONSUMO                                        629
LOGISTA                                               483
LOREAL COSMETICA(COLORIDO)                            449
LOREAL MAYBELLINE [ MAYBELLINE ]                      395
                                                     ...
OCEANYC IMPORTACIONES                                   1
PERFUMERIAS ILLAGAR, S.L.                               1
INQUIBA COMERCIAL ROYALE AMBREE [ ROYALE AMBREE, ]      1
CEDERROTH DISTREET MUM [ MUM ]                          1
CHABELI S.L                                             1
Length: 121, dtype: int64

In [19]:
print(df_art.groupby('Proveedor').size().idxmax())  # esto nos dice que el mayor proveedor es DPH S. L .

print(df_art.groupby('Proveedor').size()['DPH S. L .'])  # con 745 productos

DPH S. L .
745

# Análisis por "CLASIFICACION":

In [20]:
df_art.groupby('Clasificación').size().sort_values(ascending = False)
# tenemos 69 tipos de articulos, aquí ordenados por cantidad

Clasificación
ASEO PERSONAL                        2399
LIMPIEZA                             2137
COLORIDO CONSUMO                     1435
PERFUMERIA CONSUMO                    550
PERFUMERIA SELECTIVA                  524
                                     ...
COMPRESAS Y PANALES INCONTINENCIA       1
COLONIA ESTUCHE CONSUMO INFANTIL        1
CERA Y QUITACERAS SUELOS                1
AMBIENTADORES ELECTRICOS                1
VARIOS                                  1
Length: 69, dtype: int64

# Análisis por "EAN":

In [21]:
print(len(df_art) - len(df_art.groupby('EAN')))
# hay 4 codigos de barras (EAN) que se repiten

df_art.groupby('EAN').size().sort_values(ascending = False)
# Vemos que los 4 primeros codigos EAN tienen 2 articulos asociados cada uno

4

EAN
8410498825092    2
8411582392209    2
8431096066205    2
8410469300320    2
8411135354029    1
                ..
7702018466726    1
7702018464579    1
7702018459780    1
7702018458110    1
9802389006137    1
Length: 8819, dtype: int64

In [22]:
df_art[df_art.EAN == '8410498825092']
# ejemplo de dos articulos con mismo EAN pero caracteristicas ligeramente distintas

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
5306,8410498825092,,INSEC ORO LACA 1AÑO 400,1.777,3.30,21,3.99,1.52,85.7,46.1,0,637,QUIMICAS ORO,LIMPIEZA
5307,8410498825092,1117045,INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C,2.900,5.78,21,6.99,2.88,99.3,49.8,24,-1,QUIMICAS ORO,LIMPIEZA

# NOTAS:

In [23]:
# ¿que son exactamente las referencias? ¿por que faltan tantas? ¿qué hace Manolo cuando falta alguna?

## Pruebas

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import cosine_distances

In [25]:
def descrip_prox1(string, umbral = 0.4):
    
    # Crear la matriz de características TF-IDF para las descripciones existentes
    vectorizer = TfidfVectorizer()
    features = vectorizer.fit_transform(df_art['Nombre'])

    # Vectorizar la nueva descripción utilizando el mismo vectorizador TF-IDF
    nueva_caracteristica = vectorizer.transform([string])

    # Calcular la similitud de la nueva descripción con las existentes mediante la distancia del coseno
    # estas distancias serán valores entre 0 y 1
    distances = cosine_distances(nueva_caracteristica, features)

    # si la distancia es menor de la indicada en el umbral, se guarda en la lista "indices_cercanos"
    indices_cercanos = [i for i, distancia in enumerate(distances[0]) if distancia <= umbral]

    # Obtener las descripciones cercanas del DataFrame original
    descripciones_cercanas = df_art.iloc[indices_cercanos].Nombre.tolist()

    # print("Descripciones cercanas:")
    # for descripcion in descripciones_cercanas:
    #     print(descripcion)
    
    return descripciones_cercanas

In [26]:
descrip_prox1("INSEC OROS PERMANENTE 1 AÑO LACA RASTREROS 520C", 0.78)

['DEKADE LAPIZ CEJAS PERMANENTE N20 NEGRO',
 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C',
 'INSEC ZUM RASTREROS CHINCHES Y PULGAS 405C.C.']

In [27]:
df_art[(df_art.Nombre == 'DEKADE LAPIZ CEJAS PERMANENTE N20 NEGRO') | (df_art.Nombre == 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C') | (df_art.Nombre == 'INSEC ZUM RASTREROS CHINCHES Y PULGAS 405C.C.')]

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
3438,8435050961209,1097869,DEKADE LAPIZ CEJAS PERMANENTE N20 NEGRO,3.039,5.78,21,6.99,2.74,90.2,47.4,4,21,NAYPES,COLORIDO CONSUMO
5307,8410498825092,1117045,INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C,2.900,5.78,21,6.99,2.88,99.3,49.8,24,-1,QUIMICAS ORO,LIMPIEZA
5334,8420236032460,1038392,INSEC ZUM RASTREROS CHINCHES Y PULGAS 405C.C.,3.000,5.74,21,6.95,2.74,91.3,47.7,-69,4,GROSSEN VERBRAUCH,LIMPIEZA

In [28]:
import Levenshtein

# def descrip_prox2(string, umbral=10):

#     # Calcular la distancia de Levenshtein entre la nueva descripción y cada descripción existente
#     distancias = [Levenshtein.distance(string, desc) for desc in df_art['Nombre']]

#     # Buscar índices de descripciones cercanas
#     indices_cercanos = [i for i, distancia in enumerate(distancias) if distancia <= umbral]

#     # Obtener las descripciones cercanas del DataFrame original
#     descripciones_cercanas = list(df_art.iloc[indices_cercanos]['Nombre'])

#     # Imprimir las descripciones cercanas
#     print("Descripciones cercanas:")
#     for descripcion in descripciones_cercanas:
#         print(descripcion)



def descrip_prox2(string, umbral_factor=0.1):
    # Calcular la distancia de Levenshtein entre la nueva descripción y cada descripción existente
    distancias = [Levenshtein.distance(string, desc) for desc in df_art['Nombre']]
    
    # Calcular la longitud promedio de las descripciones existentes
    longitud_promedio = len(df_art.Nombre.sum())/len(df_art)
    
    # Calcular el umbral relativo
    umbral = umbral_factor * longitud_promedio
    
    # Buscar índices de descripciones cercanas
    indices_cercanos = [i for i, distancia in enumerate(distancias) if distancia <= umbral]
    
    # Obtener las descripciones cercanas del DataFrame original
    descripciones_cercanas = list(df_art.iloc[indices_cercanos]['Nombre'])
    
    # print("Descripciones cercanas:")
    # for descripcion in descripciones_cercanas:
    #     print(descripcion)
    
    return descripciones_cercanas

In [29]:
descrip_prox2("INSECTICIDA OROS PERM 1 AÑO LACA RASTREROS 520C", 0.75)
# parecia dificil estimar un buen threshold de lo que se considera cerca, pues no se tenía en cuenta la longitud de las descripciones
# añadiendo ese factor de umbral, ahora el umbral es un porcentaje de la longitud media y creo que tiene mucho mas sentido

['INSEC ORO CUCAS LACA 1AÑO 750',
 'INSEC ORO LACA 1AÑO 400',
 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C']

In [30]:
df_art[(df_art.Nombre == 'INSEC ORO CUCAS LACA 1AÑO 750') | (df_art.Nombre == 'INSEC ORO LACA 1AÑO 400') | (df_art.Nombre == 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C')]

# la funcion que utiliza Levenshtein parece la que mejor captura las similitudes entre los articulos
# ademas de por supuesto capturar el articulo que tiene descripcion casi identica a la proporcionada, los otros dos capturados guardan una relacion bastante estrecha con este

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
5305,8410498290166,,INSEC ORO CUCAS LACA 1AÑO 750,4.220,5.78,21,6.99,1.56,37.0,27.0,-38,50,QUIMICAS ORO,LIMPIEZA
5306,8410498825092,,INSEC ORO LACA 1AÑO 400,1.777,3.30,21,3.99,1.52,85.7,46.1,0,637,QUIMICAS ORO,LIMPIEZA
5307,8410498825092,1117045,INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C,2.900,5.78,21,6.99,2.88,99.3,49.8,24,-1,QUIMICAS ORO,LIMPIEZA

In [31]:
import jellyfish

def descrip_prox3(string, umbral=0.4):

    # Calcular la similitud de Jaro-Winkler entre la nueva descripción y las descripciones existentes
    descripciones = list(df_art['Nombre'])
    similitudes = [jellyfish.jaro_winkler(string, desc) for desc in descripciones]

    # Buscar índices de descripciones cercanas
    indices_cercanos = [i for i, similitud in enumerate(similitudes) if similitud >= umbral]

    # Obtener las descripciones cercanas del DataFrame original
    descripciones_cercanas = [descripciones[i] for i in indices_cercanos]

    # print("Descripciones cercanas:")
    # for descripcion in descripciones_cercanas:
    #     print(descripcion)
    
    return descripciones_cercanas

In [32]:
descrip_prox3("INSEC OROS PERMANENTE 1 AÑO LACA RASTREROS 520C", 0.836)

['INSEC ORION ELE RESPECT APA+REC',
 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C',
 'INSECT RAID  ELE FAMILY SIN OLOR APARATO+REC.30 NOCHES']

In [33]:
df_art[(df_art.Nombre == 'INSEC ORION ELE RESPECT APA+REC') | (df_art.Nombre == 'INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C') | (df_art.Nombre == 'INSECT RAID  ELE FAMILY SIN OLOR APARATO+REC.30 NOCHES')]

,EAN,Referencia,Nombre,Coste,Precio,tipo_IVA,P.V.P.,Beneficio,%MC,%MV,Stock,Dias_ultima_venta,Proveedor,Clasificación
5295,8411660039156,1063054,INSEC ORION ELE RESPECT APA+REC,2.244,3.26,21,3.95,1.02,45.3,31.2,159,0,MARCA HOME CARE LIMPIEZA,LIMPIEZA
5307,8410498825092,1117045,INSEC ORO PERMANENTE 1 AÑO LACA RASTREROS 520C,2.900,5.78,21,6.99,2.88,99.3,49.8,24,-1,QUIMICAS ORO,LIMPIEZA
5341,5000204190267,1153588,INSECT RAID ELE FAMILY SIN OLOR APARATO+REC.3...,2.418,4.12,21,4.99,1.70,70.4,41.3,7,75,IMPREX JOHNSONS [ JOHNSON WAX ],LIMPIEZA

In [34]:
# Creo la columna clase, asignando en principio a cada artículo su indice como clase
df_art['Clase'] = np.arange(len(df_art))

### la funcion "descrip_prox" toma un diccionario (nueva fila o registro que queremos añadir. las claves del diccionario serán las columnas del dataframe), el dataframe en el que vamos a buscar (debe contar al menos con las columnas 'Nombre' y 'Clase'), y los umbrales de las funciones de distancia que por defecto serán 0.9. 
Siempre devuelve un dataframe: con la nueva fila añadida y la clase del articulo como corresponda, o el dataframe sin modificacion alguna en caso de que finalmente so se añada el articulo. He querido hacerlo así para que se pueda sobreescribir siempre el dataframe con el output de la funcion (ya que si no lo hicieramos asi, en el caso de no añadir un articulo, si la funcion no devuelve nada y sobreescribimos el dataframe, tendremos problemas mas tarde).

Nota: el diccionario con el nuevo registro que le pasamos a la funcion, tendrá siempre el valor 0 en "Clase". Lo importante es asegurarse de no ponerle un valor mayor que el maximo de la columna "Clase".

In [35]:
# primero voy a guardar df_art ya preprocesado en un csv
# df_art.to_csv("df_art.csv", index=False)

In [36]:
def descrip_prox(dic, df, U1=0.9, U2=0.9):
    
    string = dic['Nombre']
    
    set1 = set(descrip_prox1(string, U1))
    set2 = set(descrip_prox2(string, U2))
    
    cercanos = list(set1 & set2)
    cercanos2 = list(set1 | set2)
    
    while True:
        if len(cercanos) == 0:
            if len(cercanos2) > 0:
                if len(cercanos2) > 4:
                    U1 -= 0.1
                    U2 -= 0.1
                    set1 = set(descrip_prox1(string, U1))
                    set2 = set(descrip_prox2(string, U2))
                    cercanos = list(set1 & set2)
                    cercanos2 = list(set1 | set2)
                    continue
                else:
                    inp = int(input(f'Existen algunos artículos con cierto parecido: "{cercanos2}". \nSi aún así desea añadirlo a la base de datos, introduzca: 1. \nEn caso contrario, introduzca: 0. \n'))
                    if inp == 0:
                        print('El nuevo artículo no se añadió finalmente.')
                        return df
                    elif inp == 1:
                        df = df.append(dic, ignore_index=True)
                        i = int(input('\nIntroduzca la posición en la lista del artículo que desea identificar con su nuevo artículo. \n'))
                        nombre = cercanos2[i-1]
                        a = df[df.Nombre == nombre].index
                        df.iloc[-1, -1] = df.iloc[a, -1]
                        return df
            else:
                df = df.append(dic, ignore_index=True)
                df.iloc[-1, -1] = df.Clase.max() + 1
                return df
        
        elif len(cercanos) == 1:
            cercano = str(*cercanos)
            inp = int(input(f'Ya existe un artículo muy parecido: "{cercano}". \nSi aún así desea añadirlo a la base de datos, introduzca: 1. \nEn caso contrario, introduzca: 0. \n'))
            if inp == 0:
                print('El nuevo artículo no se añadió finalmente.')
                return df
            elif inp == 1:
                df = df.append(dic, ignore_index=True)
                a = df[df.Nombre == cercano].index
                df.iloc[-1, -1] = df.iloc[a, -1]
                return df
        
        else:
            if len(cercanos) > 4:
                U1 -= 0.1
                U2 -= 0.1
                set1 = set(descrip_prox1(string, U1))
                set2 = set(descrip_prox2(string, U2))
                cercanos = list(set1 & set2)
                cercanos2 = list(set1 | set2)
                continue
            else:
                inp = int(input(f'Existen artículos muy similares: "{cercanos}". \nSi aún así desea añadirlo a la base de datos, introduzca: 1. \nEn caso contrario, introduzca: 0. \n'))
                if inp == 0:
                    print('El nuevo artículo no se añadió finalmente.')
                    return df
                elif inp == 1:
                    df = df.append(dic, ignore_index=True)
                    i = int(input('\nIntroduzca la posición en la lista del artículo que desea identificar con su nuevo artículo. \n'))
                    nombre = cercanos[i-1]
                    a = df[df.Nombre == nombre].index
                    df.iloc[-1, -1] = df.iloc[a, -1]
                    return df

#### Ya tenemos un artículo llamado 'AMONIACO VOLVONE LIGHT 750ML'. Introducimos un articulo nuevo cuyo nombre es 'AMONIACO VOLV 700 + 50 ML', y aunque es en realidad el mismo, el sistema no sabría que ya lo tenemos.

In [37]:
d = {'EAN': 23423444, 'Referencia': 999, 'Nombre': 'AMONIACO VOLV 700 + 50 ML', 'Coste': 3, 'Precio': 76, 'tipo_IVA': 98, 'P.V.P.': 984,
       'Beneficio': 23, '%MC': 0.43, '%MV': 999, 'Stock': 999, 'Dias_ultima_venta': 999, 'Proveedor': 'jkhb',
       'Clasificación': 999, 'Clase': 0}

df_art = descrip_prox(d, df_art)

Existen algunos artículos con cierto parecido: "['AMONIACO VOLVONE LIGHT 750ML', 'AMONIACO PQS 1000ML', 'AMONIACO VOLVONE 500ML']".
Si aún así desea añadirlo a la base de datos, introduzca: 1.
En caso contrario, introduzca: 0.
 0

El nuevo artículo no se añadió finalmente.

In [38]:
# CALCULAR CERCANIA TAMBIEN POR PRECIO Y COSTE Y, SI FINALMENTE COINCIDE CON OTRO ARTICULO, NO CREAR CLASES NI NADA, SIMPLEMENTE QUEDARME CON EL QUE MAS RECIENTEMENTE SE VENDIÓ Y TIRAR EL OTRO

In [39]:
df_art.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8823 entries, 0 to 8822
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EAN                8823 non-null   object
 1   Referencia         8823 non-null   object
 2   Nombre             8823 non-null   object
 3   Coste              8823 non-null   object
 4   Precio             8823 non-null   object
 5   tipo_IVA           8823 non-null   object
 6   P.V.P.             8823 non-null   object
 7   Beneficio          8823 non-null   object
 8   %MC                8823 non-null   object
 9   %MV                8823 non-null   object
 10  Stock              8823 non-null   object
 11  Dias_ultima_venta  8823 non-null   object
 12  Proveedor          8823 non-null   object
 13  Clasificación      8823 non-null   object
 14  Clase              8823 non-null   int32
dtypes: int32(1), object(14)
memory usage: 999.6+ KB